@startmindmap


*[#DeepSkyBlue] WhileNotSuccess
    *[#SkyBlue] Sequence
        * BLOCK UpdateCurrentTime 
        * BLOCK UpdateMarkerVisible 
        * BLOCK UpdateSearchTimedOut
        *[#Khaki] ConditionalExecutor marker_visible
            ' старт Точная посадка
            *[#SkyBlue] True: Sequence
                * BLOCK DeinitMarkerSearch
                * BLOCK UpdateSearchStartTime
                *[#DeepSkyBlue] WhileNotSuccess 
                    *[#SkyBlue] Sequence
                        * BLOCK RegulatePositionFunc
                        * goal_height=0.0, min_speed=PLD_MIN_ALT_SPD, yaw_speed = 180.0 / M_PI * pid_yaw.pid(alpha_rad, current_time - last_pid_time) --> blackboard
                        * BLOCK RegulateHeightFunc
                        * BLOCK UpdateLastPIDTime
                        * Установить скорости относительно СК дрона = x_speed, y_speed, z_speed, -yaw_speed
                        * BLOCK CheckLandedState 
                ' стоп Точная посадка
                ' *[#MediumPurple] CheckSearchTimedOut
            *[#Khaki] False: ConditionalExecutor search_timed_out
                *[#SkyBlue] True: Sequence
                    * BLOCK DeinitMarkerSearch
                    * BLOCK Land
                *[#SkyBlue] False: Sequence
                    * Определить uav_above_land_guarantee_threshold
                    *[#Khaki] ConditionalExecutor uav_above_land_guarantee_threshold
                        *[#SkyBlue] True: Sequence
                            * Определить uav_lower_than_search_altitude
                            *[#Khaki] ConditionalExecutor uav_lower_than_search_altitude
                                *[#SkyBlue] True: Sequence
                                    * goal_height=PLD_SRCH_ALT, min_speed=PLD_MIN_ALT_SPD, yaw_speed = 0.0 --> blackboard
                                    * BLOCK RegulateHeightFunc
                                    * Condition marker_visible
                                    * Condition current_height >= PLD_SRCH_ALT
                                    * BLOCK CheckLandedState
                                *[#SkyBlue] False: Sequence
                                    * goal_height=0.0, min_speed=PLD_MIN_ALT_SPD, yaw_speed = 0.0 --> blackboard
                                    * BLOCK RegulateHeightFunc
                                    * Condition marker_visible
                                    * Condition current_height < PLD_SRCH_ALT
                                    * BLOCK CheckLandedState
                        * False: BLOCK Land

' *[#DeepSkyBlue] WhileNotSuccess 
'     *[#Orange] Fallback
'         * Condition alpha_rad > 0.1
'         *[#SkyBlue] Sequence
'             * BLOCK UpdateSearchStartTime
'             * BLOCK UpdateCurrentTime
'             * BLOCK UpdateMarkerVisible
'             * BLOCK UpdateSearchTimedOut
'             * BLOCK RegulatePositionFunc()
'             * BLOCK RegulateHeightFunc(goal_height=PLD_SRCH_ALT, min_speed=0.0)
'             * yaw_speed = 180.0 / M_PI * pid_yaw.pid(alpha_rad, current_time - last_pid_time) --> blackboard
'             * Установить скорости x_speed, y_speed, z_speed, -yaw_speed

@endmindmap
