@startmindmap

*[#DeepSkyBlue] WhileNotSuccess 
    *[#Orange] Fallback
        * Condition alpha_rad > 0.1
        *[#SkyBlue] Sequence
            * BLOCK UpdateSearchStartTime
            * BLOCK UpdateCurrentTime
            * BLOCK UpdateMarkerVisible
            * BLOCK UpdateSearchTimedOut
            * BLOCK RegulatePositionFunc()
            * BLOCK RegulateHeightFunc(goal_height=PLD_SRCH_ALT, min_speed=0.0)
            * yaw_speed = 180.0 / M_PI * pid_yaw.pid(alpha_rad, current_time - last_pid_time) --> blackboard
            * Установить скорости x_speed, y_speed, z_speed, -yaw_speed

@endmindmap
