@startmindmap
*[#LimeGreen] Parallel (Strict)
    * Получение параметров - x_rad, y_rad, telem, last_time_marker_was_seen
    *[#SkyBlue] Sequence
        * Получить миссию и параметры миссии
        * Установить начальное значение current_time
        * Установить начальное значение marker_visible
        *[#Pink] Decorator Invert
            * BLOCK CheckLandedState
        * BLOCK CheckMission
        * BLOCK CheckRTLParams
        * BLOCK PathFollowingOffboard
        * Установить начальное значение search_start_time = current_time
        * Определить и добавить в blackboard search_timed_out = false
        * Определить и добавить в blackboard marker_visible = true
        *[#SkyBlue] Sequence 
            * BLOCK UpdateCurrentTime
            * BLOCK UpdateMarkerVisible
            *[#Orange] Fallback 
                * Condition marker_search_is_set_up
                * BLOCK SetupMarkerSearch
            *[#Pink] Decorator Invert
                *[#SkyBlue] Sequence
                    * Condition search_timed_out
                    *[#Pink] Decorator Invert
                        * BLOCK Land
            *[#Orange] Fallback
                * BLOCK CheckLandedState
                *[#Orange] Fallback
                    * Condition marker_visible
                    * BLOCK Искать маркер
        * BLOCK DeinitMarkerSearch
        * pid_regulator::PID pid(PLD_KP, PLD_KI, PLD_KD) -> blackboard
        * pid_regulator::PID pid_yaw(0.5, 0.0, 0.0) -> blackboard
        * pid_regulator::PID pid_z(0.3, 0.0, 0.1) -> blackboard
        * Создать last_pid_time = 0 и dr = sqrt(x_rad ^ 2 + y_rad ^ 2) в blackboard
        ' * BLOCK CenterAboveMarker
        *[#LimeGreen] Parallel (Strict)
            * BLOCK CheckMarkerCentered
            * BLOCK UpdateCurrentTime
            * BLOCK UpdateMarkerVisible
            * BLOCK UpdateSearchTimedOutSearchTimeout
            *[#Orange] Fallback
                *[#LimeGreen] Parallel (Strict)
                    *[#SkyBlue] Sequence
                        * Condition marker_visible
                        * BLOCK UpdateSearchStartTime
                    *[#SkyBlue] Sequence
                        * BLOCK CheckMarkerCentered
                        * BLOCK RegulatePositionFunc
                        * BLOCK RegulateHeightFunc
                        * BLOCK UpdateLastPIDTime
                        * Установить скорости относительно СК дрона = x_speed, y_speed, z_speed, yaw(0.0)
                *[#Orange] Fallback
                    *[#Pink] Decorator Invert
                        *[#SkyBlue] Sequence
                            * Condition search_timed_out
                            *[#Pink] Decorator Invert
                                * BLOCK Land
                *[#SkyBlue] Sequence 
                    * BLOCK UpdateCurrentTime
                    * BLOCK UpdateMarkerVisible
                    *[#Orange] Fallback 
                        * Condition marker_search_is_set_up
                        * BLOCK SetupMarkerSearch
                    *[#Pink] Decorator Invert
                        *[#SkyBlue] Sequence
                            * Condition search_timed_out
                            *[#Pink] Decorator Invert
                                * BLOCK Land
                    *[#Orange] Fallback
                        * BLOCK CheckLandedState
                        *[#Orange] Fallback
                            * Condition marker_visible
                            * BLOCK Искать маркер
                    

@endmindmap
