name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Install ROS2
      run: |
        sudo apt update && sudo apt install -y lsb-release wget
        echo "deb [arch=amd64] http://packages.ros.org/ros2/ubuntu jammy main" | sudo tee /etc/apt/sources.list.d/ros2-latest.list
        wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
        sudo apt update
        sudo apt install ros-humble-desktop
        sudo apt install ros-dev-tools


    - uses: actions/checkout@v4
    - name: Build
      run: |
        mkdir -p src_loc/uavsdk
        find . -maxdepth 1 ! -name 'src_loc' -type f -exec mv {} src_loc/uavsdk \;
        mv src_loc src
        colcon build

     
    - name: Source ROS2 Workspace
      shell: bash
      run: source /opt/ros/humble/setup.bash && source install/setup.bash


    - name: Run ROS2 Node
      shell: bash
      run: |
        source /opt/ros/humble/setup.bash && \
        source install/setup.bash && \
        ros2 run uavsdk bh_test

