name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04
    # container: osrf/ros:humble-desktop

    steps:
    - name: Install ROS2
      run: |
        sudo apt update && sudo apt install -y lsb-release wget
        echo "deb [arch=amd64] http://packages.ros.org/ros2/ubuntu jammy main" | sudo tee /etc/apt/sources.list.d/ros2-latest.list
        wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
        sudo apt update
        sudo apt install ros-humble-desktop
        sudo apt update && sudo apt install -y ros-humble-ament-cmake
        sudo apt install ros-dev-tools
    
    - uses: actions/checkout@v4
    - name: Set up ROS 2 Humble
      shell: bash
      run: |
        sudo apt update  
        sudo apt install software-properties-common -y 
        sudo apt install python3-pip -y
        source /opt/ros/humble/setup.bash

    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt install -y libzmq3-dev && \
        mkdir third-party && cd third-party && \
        touch COLCON_IGNORE && \
        cd ~ && \
        git clone https://github.com/nlohmann/json.git && \
        cd json && \
        mkdir build && cd build && \
        cmake .. && \
        cmake --build . && \
        sudo cmake --install .
        cd ../../..


    - name: Build
      shell: bash
      run: |
        sudo rosdep init
        rosdep update
        rosdep install -i -y --from-path . --rosdistro humble
        source /opt/ros/humble/setup.bash
        colcon build --symlink-install
     
    - name: Source ROS2 Workspace
      shell: bash
      run: source /opt/ros/humble/setup.bash && source ./install/setup.bash

    - name: Run tests and view results
      shell: bash
      run: |
        source /opt/ros/humble/setup.bash && \
        colcon test --ctest-args "--output-on-failure" && colcon test-result
