name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04
    container: osrf/ros:humble-desktop

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        mkdir -p src_loc/uavsdk
        find . -maxdepth 1 ! -name 'src_loc' -type f -exec mv {} src/uavsdk \;
        mv src_loc src
        colcon build

    - name: Source ROS2 Workspace
      run: source /opt/ros/humble/setup.bash && source install/setup.bash


    - name: Run ROS2 Node
      run: |
        source /opt/ros/humble/setup.bash && \
        source install/setup.bash && \
        ros2 run uavsdk bh_test

