name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Install system dependencies
      run: |
        sudo apt-get update && \
        sudo apt-get -y install googletest cmake libgtest-dev git clang-12 build-essential

    - name: Install Dependencies
      shell: bash
      run: |
        mkdir third-party && cd third-party && \
        touch COLCON_IGNORE && \
        git clone https://github.com/nlohmann/json.git --depth 1 && \
        cd json && \
        mkdir build && cd build && \
        cmake .. && \
        cmake --build . && \
        sudo cmake --install . && \
        cd ../../..

    - name: Build
      shell: bash
      run: |
        cd ..
        cmake -S . -B build -DBUILD_TESTING=true && \
        cmake --build build
     
    - name: Test 
      shell: bash
      run: ctest -C Debug
